apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: dsmsnewapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dsmsnewapp 
    spec:
      containers:
        - name: dsmsnewapp 
          image: desattiracr.azurecr.io/dsmsnewapp
          ports:
          - containerPort: 80